#Adding Element in list
l=[1,3,5,7,9]
print("Original list:",l)
l.append(6)
print("Added Elements in List using append:",l)
l.insert(2, 45)
print("Added Elements in List using insert:",l)
l.extend([21, 5, 67])
print("Added Elements in List using extend:",l)
l.remove(3)
print("Removing Element in list using remove",l)
l.pop()
print("Removing Element in list using pop",l)
l.clear()
print("Removing Element in list using clear:",l)
