t=(2,3,4,5,6,7)
print("Original Tuple:",t)
l=list(t)
l.append(9)
tu=tuple(l)
print("Adding element in Tuple using Append",tu)
ti=list(tu)
ti.remove(5)
tup=tuple(ti)
print("Removing element in Tuple using Remove",tup)
